### ISSUE TITLE
[3.3] Plugin incompatible to KeePass 2.56

### ISSUE THREAD

**Issue by akuropka** [sirAndros/KeePassWinHello#105]
**Describe the bug**

Plugin cannot be compiled, the "state is invalid".

**To Reproduce**

1. Clope KeePass if running.
2. Copy Plugin (v3.3) into Plugins Folder
3. Start KeePass.

**Expected behavior**

Plugin is compiled, enabled and running.

**Screenshots**

![20240407_202752_KeePass](https://github.com/sirAndros/KeePassWinHello/assets/22570574/1275fe3a-d803-4d7d-9a52-55c33acc0c57)

## Context

Please complete the following information:

| Component | Version |
|-----------|---------|
| Operating System | Microsoft Windows [Version 10.0.22635.3430] |
| KeePass | 2.56 (64-bit) |
| Plugin | https://github.com/sirAndros/KeePassWinHello/commit/d7b7d1f6b129690c7396d6735294d14eb82d424b |

**Hardware info**

- PC Motherboard or laptop/tablet model: HP Pavilion 17-cd1375ng
- Used biometric sensors: VeriMark IT Fingerprint Key
- TPM module info: 2.0 - INTC v500.14.70.2228
 
 **Plugin settings**
 
 - [X] Is persistent mode enabled ("Store keys in Windows Credential Manager" checked)
 
 **KeePass settings and environment**
 
 - [ ] Is secure desktop enabled
 - [ ] Is KeePass running under Administrator (in elevated process)
 - [ ] Was it right after hibernation
 - [ ] Was KeePass minified or closed
 
 - Installed plugins: KeePassNatMsg, KPEnhancedEntryView, SourceForgeUpdateChecker
 - Any specific settings in KeePass/Plugin: N/A

**Comment by akuropka** [comment]
@sirAndros, thank you for your quick attention.

**Comment by sirAndros** [comment]
Hi @akuropka,
thank you very much for opening the issue. I hope not many people are affected. 
Could you please check version 3.3.1?

**Comment by akuropka** [comment]
v3.3.1 seems to work 👍

**Comment by sirAndros** [comment]
Thank you!
