### ISSUE TITLE
approve chocolatey packages

### ISSUE THREAD

**Issue by dampee** [sirAndros/KeePassWinHello#108]
**Is your feature request related to a problem? Please describe.**
I am using chocolatey to install and maintain my software on my computer.
One of the reasons I choose this plugin is that it has a chocolatey package 🙏.
After releasing a new package is uploaded but not approved.

**Describe the solution you'd like**
An automatic (?) approval of the new package

**Additional context**
While there is a new version, chocolatey has no approved version yet: 

https://community.chocolatey.org/packages/keepass-plugin-winhello#versionhistory
![image](https://github.com/sirAndros/KeePassWinHello/assets/1857460/77ade780-7696-4a64-a732-aff18967812e)

**Comment by sirAndros** [comment]
Fixed
