### ISSUE TITLE
Even if I set the configuration option "Revoke current key in case Windows Hello prompt was cancelled" to false, after restarting KeePass, the configuration option always changes to true.

### ISSUE THREAD

**Issue by Plyer** [sirAndros/KeePassWinHello#109]
**Describe the bug**

Even if I set the configuration option "Revoke current key in case Windows Hello prompt was cancelled" to false, after restarting KeePass, the configuration option always changes to true.

I have confirmed that I have checked the KeePass.config.xml file, and WindowsHello.QuickUnlock.RevokeOnCancel=false. Then after restarting KeePass, WindowsHello.QuickUnlock.RevokeOnCancel is still false in the KeePass.config.xml file. However, in the KeePass Tools-Options-WindowsHello configuration, WindowsHello.QuickUnlock.RevokeOnCancel is checked and in effect.

**To Reproduce**

1. In the KeePass Tools-Options-WindowsHello configuration, uncheck WindowsHello.QuickUnlock.RevokeOnCancel, leaving other configurations as default.
2. After completely closing and restarting KeePass, when checking the Tools-Options-WindowsHello configuration, it is found that WindowsHello.QuickUnlock.RevokeOnCancel is checked.

**Expected behavior**

After restarting KeePass, it should retain the modified configuration option.

**Screenshots**

![image](https://github.com/sirAndros/KeePassWinHello/assets/16233912/42d43025-ad2f-46a4-bc19-ae91c7905939)

## Context

Please complete the following information:

| Component | Version |
|-----------|---------|
| Operating System | Windows 11 23H2 22631.3447 |
| KeePass | 2.56 64bit |
| Plugin | 3.3.1.0 |

**Hardware info**

- PC Motherboard or laptop/tablet model
- Used biometric sensors
- TPM module info (`Win`+`R` => `tpm.msc`)
 
 **Plugin settings**
 
 - [ ] Is persistent mode enabled ("Store keys in Windows Credential Manager" checked)
 
 **KeePass settings and environment**
 
 - [ ] Is secure desktop enabled
 - [ ] Is KeePass running under Administrator (in elevated process)
 - [ ] Was it right after hibernation
 - [ ] Was KeePass minified or closed
 
 - Installed plugins (if any)
 - Any specific settings in KeePass/Plugin

**Additional context**

**Comment by Plyer** [comment]
It's my fault.

**Comment by sirAndros** [comment]
Hi, @Plyer,
Could you please describe the cause, maybe we need some better text somewhere?

**Comment by Plyer** [comment]
> Hi, @Plyer, Could you please describe the cause, maybe we need some better text somewhere?

In the KeePass.config.enforced.xml configuration file, I configured WindowsHello.QuickUnlock.RevokeOnCancel=true, which caused the corresponding configuration value to remain true every time I restarted KeePass.

**Comment by sirAndros** [comment]
Thank you for explanation. 
It doesn't look like something that should be mentioned somewhere in product for me.
Are you OK to leave it just as resolution for the issue in case if someone will search for it?

**Comment by Plyer** [comment]
> Thank you for explanation. It doesn't look like something that should be mentioned somewhere in product for me. Are you OK to leave it just as resolution for the issue in case if someone will search for it?

Yes, that’s fine with me. Thank you! Your product has greatly improved my KeePass experience.
