### ISSUE TITLE
Windows Hello appears in background

### ISSUE THREAD

**Issue by gmergulhao** [sirAndros/KeePassWinHello#11]
When calling keepass to front, its window will come up in foreground but the windows from Windows Hello requiring the fingerprint does not come with it but instead opens up in background. This is inneficient as one must first switch to the Hello Windows in order tounlock the DB. Ideal Scenario would be windows Hello comes to foreground along with keepass window

**Comment by sirAndros** [comment]
Hello!
Check out version [2.2](https://github.com/sirAndros/KeePassWinHello/releases/tag/2.2)
