### ISSUE TITLE
Entering password on Secure Desktop prevents Hello prompt

### ISSUE THREAD

**Issue by LimaKilo** [sirAndros/KeePassWinHello#12]
Having the Keepass password prompt set to appear on a secure desktop prevents the Hello prompt from being there to interact with (because it's on the normal desktop). I don't know if that is something that can be worked around, but in that case it should be documented (maybe even automatically checked).

Software versions: Win 10 1809, KPWH 2.0, KeePass 2.40

**Comment by sirAndros** [comment]
Hello!
Please, check new release
https://github.com/sirAndros/KeePassWinHello/releases/tag/v2.1
