### ISSUE TITLE
Only unlock certain databases with Hello

### ISSUE THREAD

**Issue by shawndellysse** [sirAndros/KeePassWinHello#14]
I use multiple keepass databases. One is my personal database, the master db. The other databases are for work, and for one that I share with my signifigant other. 

I use KeeAutoOpen to easily open all three databases by opening the master db. The issue I'm running into is that when I attempt to use autotype while all my databases are locked, KeePassWinHello only opens on of the secondary databases (not sure how the database is chosen exactly, some times it's one sometimes it's the other), requiring me to open the application, select my primary db, and then WinHello auth into that, allowing all databases to become unlocked

I think the best way to handle this would be able to mark a database as not WinHello openable, or have a  way to tell WinHello which db should be the primary attempt

**Comment by shawndellysse** [comment]
Nevermind realized I could accomplish what I was looking for with triggers: https://keepass.info/help/kb/trigger_examples.html#multidb (documenting for future users)

**Comment by sirAndros** [comment]
Hello!
Our plugin does not chose the database to be opened. It only handle attempt of opening from KeePass or other plugins.
