### ISSUE TITLE
Version 2.1 shows up as 2.0.0.0 on plugin list

### ISSUE THREAD

**Issue by stlhrt** [sirAndros/KeePassWinHello#16]
Version 2.1 shows up as 2.0.0.0 on plugin list.

**To Reproduce**
1. Go to Tools > Plugins

**Expected behavior**
Version 2.1.0.0 is listed

**Desktop (please complete the following information):**
 - Win 10 Pro
 - KeePass Version 2.41

**Comment by sirAndros** [comment]
[https://github.com/sirAndros/KeePassWinHello/commit/865714d77c47cd134586afdaa85764a100fd1088](fixed)

**Comment by sirAndros** [comment]
Thank you! We forget push version in file :)
