### ISSUE TITLE
Error "Windows Hello is disabled on your system"

### ISSUE THREAD

**Issue by sambul13** [sirAndros/KeePassWinHello#17]
On a PC with Windows 10 Pro R1809 with latest updates, I added KeePassWinHello 2.1 to KeePass 2.41 plugins folder, and launched KeePass. Upon login with Master Password, and opening WindowsHello tab in Options, the tab error says "Windows Hello is disabled on your system". But it's actually enabled and working,  I login to the PC with fingerprint login.

**Comment by sambul13** [comment]
Also, after installing KeePassWinHello v2.1, it identifies as KeePassWinHello v2.0 .

**Comment by sirAndros** [comment]
> Also, after installing KeePassWinHello v2.1, it identifies as KeePassWinHello v2.0 .

This fixed in #16. Please, try to download again.

**Comment by sirAndros** [comment]
@sambul13, hello!
Can You check what says windows about this?
Navigate to Settings>Accounts>Sign-in Options.
Does windows determinate WinHello as available on your PC?
For my old PC its looks like this:
![image](https://user-images.githubusercontent.com/1522711/54074531-b96c0280-4293-11e9-8eab-0c954209c6a3.png)

**Comment by sambul13** [comment]
Yes, its available in Settings, and as I said before, I use it every day by fingerprint sign in to Windows. Further, I installed [Fingerprint](https://github.com/fabiocbr75/KeePassFingerprint) KeePass plugin, and it works OK, so stability can be improved. I like your plugin more since its simpler to add, but it doesn't work. :)

**Comment by sambul13** [comment]
See screenshots

![WinHello](https://user-images.githubusercontent.com/2223493/54253499-c43dc600-4525-11e9-8611-e506ff6bafdb.jpg)
![WinLogin](https://user-images.githubusercontent.com/2223493/54253500-c4d65c80-4525-11e9-9d60-790cf69b6f5b.jpg)

**Comment by sambul13** [comment]
The issue was fixed by following [this](https://github.com/sirAndros/KeePassWinHello/issues/2) solved similar issue. Basically, for home PCs not connected to a domain and Active Directory, a user needs to _Turn on convenience PIN sign-in_ in Local Security Policy, and turn off _Windows Hello for Business_, since its not used anyway. One must still add his fingerprint and convenience PIN in _Windows Sign-In Options_. The PIN can be set as complex as login password.

**Comment by sirAndros** [comment]
Thank you a lot for this research!
Can we include this as is in our _readme_?

**Comment by sirAndros** [comment]
Thank you!
Of course, it will helps only until Microsoft do breaking changes as they do usually :)
