### ISSUE TITLE
Duplicate query of webdav credentials and missing auto type dialog

### ISSUE THREAD

**Issue by kinglike1337** [sirAndros/KeePassWinHello#18]
I upgraded to KeePassWinHello 2.1 to use the secure desktop feature.

After upgrading I am facing two problems:
1. My Database is loaded from a webdav url without stored credentials (only username is stored).
I have to enter the webdav password before database unlock. This dialog is triggered two times using the new version. After that die WinHello-Dialog popups.
2. After succesful unlock the auto type dialog is missing.
The database is unlocked using the hotkey for auto type. After the problem above the autotype dialog does not appear.

After disabling secure desktop it worked again.

**Comment by kinglike1337** [comment]
Another problem concerining the autotype hotkey behaviour without secure desktop (both 2.0 and 2.1):
The autotype dialog sometimes opens in the background.
Steps:
1. Hotkey is triggered
2. Webdav password prompts opens and gets confirmed
3. WinHello prompts opens in the left corner of the desktop (maybe because the KeePass windows is hidden)
4. The autotype dialog opens, but loses focus

**Comment by sirAndros** [comment]
Hello!
We had changed some logic in our last release. Can you confirm that you still have this issue?
If so, can you disable all other plugins to prevent possible interference?

**Comment by kinglike1337** [comment]
Thank you for the information and your hardwork on this plugin.

I made a quick test using the new version 3.0:
The problem from my first comments still exists (both points).
The problem from my second comment seems to be fixed.

**Comment by sirAndros** [comment]
Thank you!
We will investigate further

**Comment by sirAndros** [comment]
This was fixed in [v3.1](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.1).
Thank you!
