### ISSUE TITLE
Failure when keepass unlock is triggered externally and 'Enter master key on secure desktop' is enabled

### ISSUE THREAD

**Issue by nmbradford** [sirAndros/KeePassWinHello#19]
Firstly - thanks for the plugin! I've just stumbled across it but its a feature I've been missing for years!

I use two plugins that trigger keepass db unlock automatically, and they both cause an issue when KeePassWinHello is in use, and 'Enter master key on secure desktop' is enabled in keepass.  

When manually invoking Keepass, KeePassWinHello operates as expected and I'm able to unlock my keepass db successfully.

When the unlock is triggered by either of these plugins, duplicate win hello dialogs appear.  Sometimes the order of their appearance is reversed, sometimes, the second only appears after the first is dismissed, but consistently only one of them will actually recognise my biometric and present an 'OK button'.  The other dialog only shows a cancel button. 

Sometimes (AFAICT, when the 'OK button enabled' dialog is behind the dialog with only a cancel button), I'm also not able to dismiss the non functional dialog at all, and what looks like a constantly rapidly spawning/disappearing window related to keepass is shown in the task bar and keepass becomes unusable (I have to manually kill the keepass process and relaunch it)

When I disable 'Enter master key on secure desktop', the problem disappears and things behave as expected.  The general problem to be reliably reproducible, though the order and exact behaviour does appear variable.

The plugins I'm using that are both triggering this are : 
 - ChromeIPass in Chrome (which leverages keepassHTTP plugin)
 - Keeagent (for accessing ssh keys in keepass)

**To Reproduce**
1. Enable 'Enter master key on secure desktop', and install / config keepasshttp + chromeipass, or keeagent.
3. With keepass started + locked, trigger db access (for instance, use the Ctrl-Shift-U to autotype user/pass into detected cred fields in chrome)
4. Observe above behaviour.

**Expected behavior**
No duplicate dialog.  No flashing 

**Screenshots**
(Moved dialogs side by side manually)
![image](https://user-images.githubusercontent.com/8855114/56398506-44c1b600-628c-11e9-8e46-7c0901d196ca.png)

**Desktop (please complete the following information):**
 - Win 10 17134.706
 - KeePass Version 2.41
 - Hardware info : Surface Laptop 2

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
you using plugin Version 2.1?

**Comment by nmbradford** [comment]
yes

**Comment by shuffle-c** [comment]
Thank you for the feedback. We changed a bit flow working with secure desktop option in v3.0, could you please check it out?

**Comment by sirAndros** [comment]
There is new algorithm for handling secure desktop in [v3.1](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.1).
Please check it out and confirm if the issue resolved.
Thank you!

**Comment by sirAndros** [comment]
Not confirmed
