### ISSUE TITLE
(SOLVED) ThermalTake TTeSports BLACK FP biometric mouse.

### ISSUE THREAD

**Issue by rjt** [sirAndros/KeePassWinHello#2]
Has anyone managed to get the ThermalTake TTeSports FP biometric mouse to work with KeePassWinHello plugin?  My desktop belongs to a tightened down domain, so not  a great test env.   KeePassWinHello generally works with our Lenovo ThinkPads, but it is hit and miss (different issue).  
[
Tt eSPORTS MO-BKV-WDLGBK-01 BLACK FP Biometric Laser Gaming Mouse](http://a.co/d/hSqmOpo) 
![image](https://user-images.githubusercontent.com/360343/45709116-cb70b200-bb48-11e8-996d-85340676c951.png)

![image](https://user-images.githubusercontent.com/360343/45709034-92384200-bb48-11e8-8412-2531a8e444a4.png)

"Windows Hello is disabled on your system.  Please activate it in the system settings"

With the late July ThermalTake "Security Center", i can now use this mouse to logon to Windows, but  Windows Hello functionality is lacking.  For instance, adding a fingerprint in the Win10 "Sign-in Options" screen is disabled for normal users.  For admin users, a popup disappears quickly.   None of these ThermalTake issues are @sirAndros problem, but wondering if other users have had any luck with it on their system.

**Comment by sirAndros** [comment]
Unfortunately, I do not even know how to help you. I'm sure you've already scoured all available sources, because the only clear conversation on the Internet is your own [question](https://community.spiceworks.com/topic/2085941-thermaltake-ttesports-biometric-mouse-to-work-with-win10-hello-mo-bkv-wdlgbk-01). Open API for ThermalTake "Security Center", of course, does not exist?

**Comment by rjt** [comment]
I am hoping to bump into someone that has the same TTeSports black fp
biometric mouse and we compare notes.

Can all the software used to compile and make your keepassWinHello plugin
be downloaded via chocolatey.org?   Or does it have to be purchased from
Microsoft?

**Comment by sirAndros** [comment]
We use Visual Studio 2017 Professional, but there is a Community edition - its completely free. You can download it here: https://visualstudio.microsoft.com/downloads/

**Comment by rjt** [comment]
Thanks to the KeePassWinHello project, i was motivated yet again to finally solve this years old problem. 
Turns out enabling some parts of Windows Hello For Business breaks the PIN which disables adding a fingerprint.  So my fingerprint would unlock the desktop even though Windows Hello was not completely working.  [Can't configure a PIN when Convenience PIN and Hello for Business policies are enabled in Windows 10](https://support.microsoft.com/en-us/help/3201940/can-t-configure-a-pin-when-convenience-pin-and-hello-for-business-poli)  helped set me straight:  

To use a convenience PIN in Windows 10 Version 1607 or later, the following Group Policy setting must be configured:

Policy: `Turn on convenience PIN sign-in`
Category: Path `Computer Configuration\Administrative Templates\System\Logon
`
 This method is not as secure as WHFB, but will have to do until our infrastructure stabilizes enough to run WHFB.  At least now i know the hardware works.

https://support.microsoft.com/en-us/help/3201940/can-t-configure-a-pin-when-convenience-pin-and-hello-for-business-poli
