### ISSUE TITLE
Update README to clearly indicate KeePass must be kept open for plugin to work

### ISSUE THREAD

**Issue by DarylWright** [sirAndros/KeePassWinHello#20]
Firstly, thanks for this great plugin! With my new fingerprint reader, access to my KeePass database has never been quicker!

It took me longer than I would have liked to get this plugin working correctly because I had the following settings enabled in KeePass:

- Exit instead of locking the workspace after the specified time
- Always exit instead of locking the workspace

Exiting made more sense to me than just locking since I had to manually enter my master password each time anyway, and it was one less window open. I'm sure this is the default setting for many users, and I think it would be helpful to explicitly indicate which lock settings provide the proper user experience. In my case, deselecting the aforementioned settings and enabling all other auto-lock settings (on minimize, on tray, etc.) did the trick.

If needed I can send a pull request with proposed changes to the README which will aim to help lessen the learning curve for this plugin.

**Comment by sambul13** [comment]
Pls also add to Readme and Wiki that Windows Hello must be configured [this way](https://github.com/sirAndros/KeePassWinHello/issues/17#issuecomment-491569634), in particular on PCs with Windows Professional and Enterprise installed, for this plugin to work.

**Comment by DarylWright** [comment]
I don't know about that particular issue and am unable to test it in my environment. It's probably better for the person who is most familiar with the issue to update the readme. Closing this issue since it was merged.
