### ISSUE TITLE
Add an option to allow Windows Hello unlock even after user manually cancelled Windows Hello prompt

### ISSUE THREAD

**Issue by GoldenHashtag** [sirAndros/KeePassWinHello#30]
**Is your feature request related to a problem? Please describe.**
Currently when Windows Hello prompt appears and user clicks cancel, standard prompt will appear, and then when you close KeePass and try to open and unlock that database again Windows Hello prompt won't appear.
But sometimes user might misclick KeePass, in this case user wants to close Windows Hello prompt, but then user cannot use Windows Hello in secondary unlock attempt because this plugin doesn't allow user to do that.

**Describe the solution you'd like**
My suggestion would be adding an option for users to decide: users can choose to let this plugin disable Windows Hello when its being used once and failed, or for users like me would love to let plugin continue asking for Windows Hello regardless of the situation.

**Describe alternatives you've considered**
Or copy the Keepass2Android unlock mechanism, an option for users to decide whether Windows Hello unlock is only bound to Quick Unlock or to Master Password. When bound to Quick Unlock, users cannot use Windows Hello when KeePass is being locked (but not closed) and the first attempt failed. When bound to Master Password, in addition to how it works with Quick Unlock, user can also restore the functionality of Windows Hello unlock after restarting KeePass.
(I don't know why😂, I thought the first solution would be better)

**Additional context**

**Comment by shuffle-c** [comment]
Thank you for the suggestion! This is a good solution, and easy to implement. We'll have a minor release soon with this option added.

**Comment by sirAndros** [comment]
This was implemented in [v3.1](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.1).
Thank you!
