### ISSUE TITLE
KeePassWinHello 3.0 error when storing keys in Windows Credential Manager

### ISSUE THREAD

**Issue by mullenat** [sirAndros/KeePassWinHello#33]
**Describe the bug**
KeePassWinHello 3.0 error when storing keys in Windows Credential Manager.

Error states:

"Something went wrong. Please report the issue in our Github
repository with the following technical info.
KeePassWinHello.AuthProviderSystemErrorException: External error occurred
Error code: 80090029
  at
KeePassWinHello.WinHelloProvider.SECURITY_STATUS.CheckStatus(Int32 ignoreStatus)
  at
KeePassWinHello.WinHello.WinHelloProvider.CreatePersisstentKey(Boolean overwriteExisting)
  at
KeePassWinHello.WinHello.WinHelloProvider.ClaimCurrentCacheType(AuthCacheType authCacheType)
  at
KeePassWinHello.KeyManager.ClaimCurrentCacheType(AuthCacheType authCacheType)
  at KeePassWinHello.OptionsPanel.SaveSettings(Settings settings)

**To Reproduce**
1. Go to 'Tools' menu
2. Click on 'Options...'
3. Click on 'WindowsHello' Tab
4. Click on 'Store keys in the Windows Credential Manager'
5. Click on 'OK'
6. See error

**Expected behavior**
Expected KeePassWinHello to create new key and successfully store in in the Windows Credential Manager 
**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803 with latest 2019-08 patches
 - KeePass Version: 2.42.1
 - KeePass Plugins versions:
   - DatabaseBackup: 2.0.8.6
   - Favicon Downloader: 1.9
   - IOProtocolExt: 1.16
   - KeePassWinHello: 3.0
   - KeeResize: 1.12
   - KPScript: 2.42.1
 - Hardware info: HP ZBook G5

**Additional context**
Windows Hello credentials set to accept a PIN or Fingerprint

![2019-08-27 16_51_01-KeePassWinHello](https://user-images.githubusercontent.com/265932/63809976-a278a580-c8f1-11e9-9031-96ff50a84c17.png)

**Comment by shuffle-c** [comment]
Hello, thank you for the report. Could you please tell us your OS build and edition?

**Comment by tvannuland** [comment]
Exactly the same issue here. Win10 Pro (x64) Version 1803 and on my Surface Pro (newest). Except both Hello are set for face recognition.

![KeePassWinHelloError](https://user-images.githubusercontent.com/15835471/63862643-33f91d80-c9ad-11e9-97c7-99679c9fc8b9.JPG)

**Comment by shuffle-c** [comment]
I've done some research and found out possible problem, could you please check if it works so that we could release the fixed version? You can download it by [this link](https://drive.google.com/open?id=1RGP6fX2ztNDWqEYoRco-Dv3_s9S-Mthu).
Thank you in advance!

**Comment by tvannuland** [comment]
Works fine on all my computers now as well. Looks like that fixes the issue. Thank you!

**Comment by sirAndros** [comment]
This was fixed in [v3.1](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.1).
Thank you!
