### ISSUE TITLE
cygwin1.dll missing

### ISSUE THREAD

**Issue by gio710** [sirAndros/KeePassWinHello#4]
I got installaion error saying 👍 
2 [main] sh (11284) C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF68410/0xED8410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 14756 fork: child -1 - forked process 11284 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      2 [main] sh (19600) C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF68410/0xF48410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1041165 [main] sh 14756 fork: child -1 - forked process 19600 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      2 [main] sh (8744) C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF68410/0xF88410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3090036 [main] sh 14756 fork: child -1 - forked process 8744 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      5 [main] sh (16776) C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF68410/0xDA8410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7160799 [main] sh 14756 fork: child -1 - forked process 16776 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      8 [main] sh (17816) C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF68410/0xE58410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15238499 [main] sh 14756 fork: child -1 - forked process 17816 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\xx\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by sirAndros** [comment]
Hello!
cygwin is not used in plugin, it is just git staff.
Please, download ready to use plugin from [releases](https://github.com/sirAndros/KeePassWinHello/releases), or, if you want to get exactly source code - contact GitHub support for assistance.
