### ISSUE TITLE
[NCryptDecrypt - 0x80280159] TPM_20_E_159

### ISSUE THREAD

**Issue by afrowuk** [sirAndros/KeePassWinHello#42]
**Describe the bug**
Exception after unlock using Windows Hello

**To Reproduce**
1. Windows Hello unlock prompt was displayed
2. Initially it was asking to unlock using my fingerprint reader, so selected face unlock
3. After the Windows Hello unlock popup was closed, the exception was displayed

**Expected behavior**
Unlock was successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/9802577/65854202-deb97e80-e353-11e9-8045-70b543741443.png)

**Desktop**
 - Windows 10 Pro 1903 64-bit
 - KeePass Version: 2.43
 - Hardware info: Lenovo P50 with Intel Xeon, 64 GB RAM

**Comment by rgwebster** [comment]
I have a similar issue. 
I received the following message which said to post it here. I just moved the Dropbox local storage from my C: drive to a larger E: drive to free up memory from C: The data file was on Dropbox.
************** begin error message ***********************
Something went wrong. Please report the issue in our Github
repository with the following technical info.
KeePassWinHello.AuthProviderSystemErrorException:
NCryptEncrypt
Error code: S00704C7
at
KeePassWinHe11o.WinHe11oProvider.SECURITY_STATUS.CheckSt
atus(String name, Int32 ignoreStatus)
at KeePassWinHello.WinHelloProvider.Encrypt(ByteQ data)
at KeePassWinHello.KeyCipher.Protect(ProtectedBinary key)
at KeePassWinHello,ProtectedKey..ctor(CompositeKey
compositeKey, KeyCipher keyCipher)
at KeePassWinHello.KeyManager.OnDBCIosingfObject
sender, FileClosingEventArgs e)
******************* end error message ***********************
Here is version information;
KeePass Version 2.44
XSL Stylesheets for KDBX XML Installed
KeePassLibC (1-* File Support) Version 1.38 (DxD1B2)

I am running on Windows 10 Pro 64 bit Version 1909 OS Build 18363.720
Installed 11/13/2019
Hardware: Home made AMD FX-8320 8 Core processor, 32 GB memory

**Comment by Moravuscz** [comment]
Similar issue, but before unlocking:
![image](https://user-images.githubusercontent.com/5168699/81434702-e43b3a80-9166-11ea-8f80-30d5f1257f7c.png)
Reopening database usually works fine but invalidates the stored key and asks to use the regular access method...
The prompt also sometimes appears in background, but can be alt-tabbed to front...

Windows 10 Pro 1909
KeePass v2.44 (from PortableApps.com)

**Comment by sirAndros** [comment]
Fixed in [v3.2](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.2)
