### ISSUE TITLE
Windows Hello prompt shown outside of secure desktop.

### ISSUE THREAD

**Issue by eaocto** [sirAndros/KeePassWinHello#49]
**Describe the bug**
Windows Hello prompt shown outside of secure desktop, even though secure desktop was actually oppened by keepass but promptly closed and taken to normal desktop to show windows hello prompt.

**To Reproduce**
1. Set keepass to 'enter master key on secure desktop' 
2. Unlock database
3. Secure desktop sounds appear, and secure desktop's black screen flashes promptly before Windows hello prompt is shown.

**Expected behavior**
Windows hello prompt should be shown inside secure desktop (just like UAC behaviour).

**Screenshot**
![Win hello prompt outside secure desktop](https://user-images.githubusercontent.com/44256518/67920853-50e1e500-fbd8-11e9-8e41-8576ff12a95c.png)

**Desktop (please complete the following information):**
 - OS Version 1809 build 17763.805
 - KeePass 2.39.1
 - Plugin 3.1.1.0
 
 **KeePass settings and enviroment**
 - Secure desktop enabled
 - KeePass running not under Administrator (in normal process)
 - Installed plugins: keeanywhere, keepassquickunlock (currently unused), keepassrpc (for firefox extension Kee)

**Comment by Angelelz** [comment]
I think this is expected behaviour, as you need to get out of secure desktop in order to show the windows hello prompt. If you cancel that, It defaults back to secure desktop.

**Comment by shuffle-c** [comment]
Hello,

@Angelelz is absolutely right. Windows Hello prompt, as an external process, cannot be shown inside secure desktop, so this is desined behaviour.

**Comment by sirAndros** [comment]
Furthermore, as you don't type anything from you keyboard - you don't need any keylogger protection (e.g. "secure desktop" keepass feature).
Of course, pin in not protected in this case.
If you concern about your fingerprint or face leak - it will leak if there is some vulnerability in Microsoft WinHello tech. But if so, secure desktop will not protect you at all.
