### ISSUE TITLE
cygwin missing enven after installin cygwin package

### ISSUE THREAD

**Issue by gio710** [sirAndros/KeePassWinHello#5]
Cloning into 'C:\Users\[USER]\Documents\GitHub\KeePassWinHello'...
remote: Enumerating objects: 84, done.        
remote: Counting objects:   1% (1/84)           
remote: Counting objects:   2% (2/84)           
remote: Counting objects:   3% (3/84)           
remote: Counting objects:   4% (4/84)           
remote: Counting objects:   5% (5/84)           
remote: Counting objects:   7% (6/84)           
remote: Counting objects:   8% (7/84)           
remote: Counting objects:   9% (8/84)           
remote: Counting objects:  10% (9/84)           
remote: Counting objects:  11% (10/84)           
remote: Counting objects:  13% (11/84)           
remote: Counting objects:  14% (12/84)           
remote: Counting objects:  15% (13/84)           
remote: Counting objects:  16% (14/84)           
remote: Counting objects:  17% (15/84)           
remote: Counting objects:  19% (16/84)           
remote: Counting objects:  20% (17/84)           
remote: Counting objects:  21% (18/84)           
remote: Counting objects:  22% (19/84)           
remote: Counting objects:  23% (20/84)           
remote: Counting objects:  25% (21/84)           
remote: Counting objects:  26% (22/84)           
remote: Counting objects:  27% (23/84)           
remote: Counting objects:  28% (24/84)           
remote: Counting objects:  29% (25/84)           
remote: Counting objects:  30% (26/84)           
remote: Counting objects:  32% (27/84)           
remote: Counting objects:  33% (28/84)           
remote: Counting objects:  34% (29/84)           
remote: Counting objects:  35% (30/84)           
remote: Counting objects:  36% (31/84)           
remote: Counting objects:  38% (32/84)           
remote: Counting objects:  39% (33/84)           
remote: Counting objects:  40% (34/84)           
remote: Counting objects:  41% (35/84)           
remote: Counting objects:  42% (36/84)           
remote: Counting objects:  44% (37/84)           
remote: Counting objects:  45% (38/84)           
remote: Counting objects:  46% (39/84)           
remote: Counting objects:  47% (40/84)           
remote: Counting objects:  48% (41/84)           
remote: Counting objects:  50% (42/84)           
remote: Counting objects:  51% (43/84)           
remote: Counting objects:  52% (44/84)           
remote: Counting objects:  53% (45/84)           
remote: Counting objects:  54% (46/84)           
remote: Counting objects:  55% (47/84)           
remote: Counting objects:  57% (48/84)           
remote: Counting objects:  58% (49/84)           
remote: Counting objects:  59% (50/84)           
remote: Counting objects:  60% (51/84)           
remote: Counting objects:  61% (52/84)           
remote: Counting objects:  63% (53/84)           
remote: Counting objects:  64% (54/84)           
remote: Counting objects:  65% (55/84)           
remote: Counting objects:  66% (56/84)           
remote: Counting objects:  67% (57/84)           
remote: Counting objects:  69% (58/84)           
remote: Counting objects:  70% (59/84)           
remote: Counting objects:  71% (60/84)           
remote: Counting objects:  72% (61/84)           
remote: Counting objects:  73% (62/84)           
remote: Counting objects:  75% (63/84)           
remote: Counting objects:  76% (64/84)           
remote: Counting objects:  77% (65/84)           
remote: Counting objects:  78% (66/84)           
remote: Counting objects:  79% (67/84)           
remote: Counting objects:  80% (68/84)           
remote: Counting objects:  82% (69/84)           
remote: Counting objects:  83% (70/84)           
remote: Counting objects:  84% (71/84)           
remote: Counting objects:  85% (72/84)           
remote: Counting objects:  86% (73/84)           
remote: Counting objects:  88% (74/84)           
remote: Counting objects:  89% (75/84)           
remote: Counting objects:  90% (76/84)           
remote: Counting objects:  91% (77/84)           
remote: Counting objects:  92% (78/84)           
remote: Counting objects:  94% (79/84)           
remote: Counting objects:  95% (80/84)           
remote: Counting objects:  96% (81/84)           
remote: Counting objects:  97% (82/84)           
remote: Counting objects:  98% (83/84)           
remote: Counting objects: 100% (84/84)           
remote: Counting objects: 100% (84/84), done.        
remote: Compressing objects:   1% (1/65)           
remote: Compressing objects:   3% (2/65)           
remote: Compressing objects:   4% (3/65)           
remote: Compressing objects:   6% (4/65)           
remote: Compressing objects:   7% (5/65)           
remote: Compressing objects:   9% (6/65)           
remote: Compressing objects:  10% (7/65)           
remote: Compressing objects:  12% (8/65)           
remote: Compressing objects:  13% (9/65)           
remote: Compressing objects:  15% (10/65)           
remote: Compressing objects:  16% (11/65)           
remote: Compressing objects:  18% (12/65)           
remote: Compressing objects:  20% (13/65)           
remote: Compressing objects:  21% (14/65)           
remote: Compressing objects:  23% (15/65)           
remote: Compressing objects:  24% (16/65)           
remote: Compressing objects:  26% (17/65)           
remote: Compressing objects:  27% (18/65)           
remote: Compressing objects:  29% (19/65)           
remote: Compressing objects:  30% (20/65)           
remote: Compressing objects:  32% (21/65)           
remote: Compressing objects:  33% (22/65)           
remote: Compressing objects:  35% (23/65)           
remote: Compressing objects:  36% (24/65)           
remote: Compressing objects:  38% (25/65)           
remote: Compressing objects:  40% (26/65)           
remote: Compressing objects:  41% (27/65)           
remote: Compressing objects:  43% (28/65)           
remote: Compressing objects:  44% (29/65)           
remote: Compressing objects:  46% (30/65)           
remote: Compressing objects:  47% (31/65)           
remote: Compressing objects:  49% (32/65)           
remote: Compressing objects:  50% (33/65)           
remote: Compressing objects:  52% (34/65)           
remote: Compressing objects:  53% (35/65)           
remote: Compressing objects:  55% (36/65)           
remote: Compressing objects:  56% (37/65)           
remote: Compressing objects:  58% (38/65)           
remote: Compressing objects:  60% (39/65)           
remote: Compressing objects:  61% (40/65)           
remote: Compressing objects:  63% (41/65)           
remote: Compressing objects:  64% (42/65)           
remote: Compressing objects:  66% (43/65)           
remote: Compressing objects:  67% (44/65)           
remote: Compressing objects:  69% (45/65)           
remote: Compressing objects:  70% (46/65)           
remote: Compressing objects:  72% (47/65)           
remote: Compressing objects:  73% (48/65)           
remote: Compressing objects:  75% (49/65)           
remote: Compressing objects:  76% (50/65)           
remote: Compressing objects:  78% (51/65)           
remote: Compressing objects:  80% (52/65)           
remote: Compressing objects:  81% (53/65)           
remote: Compressing objects:  83% (54/65)           
remote: Compressing objects:  84% (55/65)           
remote: Compressing objects:  86% (56/65)           
remote: Compressing objects:  87% (57/65)           
remote: Compressing objects:  89% (58/65)           
remote: Compressing objects:  90% (59/65)           
remote: Compressing objects:  92% (60/65)           
remote: Compressing objects:  93% (61/65)           
remote: Compressing objects:  95% (62/65)           
remote: Compressing objects:  96% (63/65)           
remote: Compressing objects:  98% (64/65)           
remote: Compressing objects: 100% (65/65)           
remote: Compressing objects: 100% (65/65), done.        
remote: Total 84 (delta 32), reused 66 (delta 17), pack-reused 0        
      2 [main] sh (8636) C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF78410/0xF68410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 21012 fork: child -1 - forked process 8636 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      2 [main] sh (21656) C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF78410/0xFA8410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1051201 [main] sh 21012 fork: child -1 - forked process 21656 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      2 [main] sh (2020) C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF78410/0xE68410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3105155 [main] sh 21012 fork: child -1 - forked process 2020 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      8 [main] sh (8096) C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF78410/0xEE8410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7193082 [main] sh 21012 fork: child -1 - forked process 8096 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      8 [main] sh (20632) C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF78410/0xE58410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15275823 [main] sh 21012 fork: child -1 - forked process 20632 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\[USER]\AppData\Local\GitHubDesktop\app-1.4.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by sirAndros** [comment]
Hello!
The cygwin is not used in plugin, it is just git staff.
Please, download ready to use plugin from [releases](https://github.com/sirAndros/KeePassWinHello/releases), or, if you want to get exactly source code - contact GitHub support for assistance.
