### ISSUE TITLE
Preferred setting for Windows Hello

### ISSUE THREAD

**Issue by bs0001** [sirAndros/KeePassWinHello#53]
Hi,
first thanks for your good AddOn for keepass!!
I use the Win Hello AddOn and would like to have the feature, that I can set my preferred setting for Windows Hello Login of my keepass database.
It's always fingerprint which was selected. My preferred one is with the face recognition.
It will be nice when the last used method is the standard one for the next unlock of the database or there is a setting where I can define which one is my perferred one.
It would be nice if you can implement this.
Best regards Bernd

**Comment by RvdHout** [comment]
Duplicate, see: https://github.com/sirAndros/KeePassWinHello/issues/13
But basically it comes down to simply use/unlock it a few times, after a few times it should remember the preferred item

**Comment by dhufnagel** [comment]
I have the same issue. I use it every day and unlock it several times a day, but it always keeps asking fpr fingerprints. Is there an API for Windows Hello that allows you to set the prefered authentication option?

**Comment by bs0001** [comment]
It's always the same at my windows-notebook.
I often use keepass and use Windows hello with face recognition for unlocking the workstation as well as in keepass.
In keepass there hasn't changed anything. Everytime fingerprint is selected.
I hope there will be a solution for us to fix this issue.
Kind regards
Bernd

**Comment by shuffle-c** [comment]
Thank all of you for feedback.
Alas, Windows Hello API does not have such an option. We'd like to provide solution as soon as it's possible. If you're interested in, you can track the original issue #13, as this one I'm closing.
