### ISSUE TITLE
[AllowSetForegroundWindow - 0x5] ACCESS_DENIED

### ISSUE THREAD

**Issue by Thib1404** [sirAndros/KeePassWinHello#56]
I had the following error when Microsoft Edge requested the opening of my KeePass database through KeePassHttp (This issue never happened before on either of my two pc's)

![image](https://user-images.githubusercontent.com/13148733/83851987-6a6d8100-a713-11ea-8b7e-a80687d1d849.png)
I have the following plugins enabled

![image](https://user-images.githubusercontent.com/13148733/83852932-d2709700-a714-11ea-9c9a-129315a53704.png)

**Desktop**

- Windows 10 Pro 2004 64 bit

- KeePass 2.45

**Comment by erhard895** [comment]
After adding KeePassWinHello I have the same problem on my notebook, on my PC ist everything ok:

![SharedScreenshot](https://user-images.githubusercontent.com/13258959/96852035-f67d0c80-1458-11eb-9a59-8284b7783d6c.jpg)

My PlugIn-List:
![grafik](https://user-images.githubusercontent.com/13258959/96853833-1dd4d900-145b-11eb-87c0-a4613f39c588.png)

Software Versions:
Windows 10 Pro 2004 32 bit
KeePass 2.46

**Comment by JakoPsi** [comment]
I have the same issue by one PC (32 Bit Windows 10 20H2)
![image](https://user-images.githubusercontent.com/82944597/115554770-1f1e7b80-a2af-11eb-9492-a83b5579c5f0.png)
There are no other Plugins.
![image](https://user-images.githubusercontent.com/82944597/115555248-93f1b580-a2af-11eb-9807-ccdd72910e31.png)

**Comment by sirAndros** [comment]
Hi, @JakoPsi , @erhard895 - I'd created #71 as it different problem.
As for original issue - the fix will be done in nearest release.
Thank every one for bug reports!

**Comment by sirAndros** [comment]
https://github.com/sirAndros/KeePassWinHello/issues/42#issuecomment-625946831 too

**Comment by sirAndros** [comment]
Fixed in [v3.2](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.2)
