### ISSUE TITLE
Unlocking DB with PIN makes the function insecure

### ISSUE THREAD

**Issue by elethandor** [sirAndros/KeePassWinHello#57]
Hello,

first of all, thank you for the great plugin you have provided.
I am encountering the following situation. After restarting Keepass, and having already enabled the plugin to use the windows credentials store I am able to open the DB not only using windows hello fingerprint recognition but also with a PIN (through more choices). This means that a confidential DB can be opened with 4 digits.

I would like to be able to open the DB only with windows, hello, and not to provide other choices for accessing the DB.

For sure an option would be to deactivate the PIN and use a strong password a secondary option for signing in, but I would like to be able to sign in on windows using the options:
1. windows hello
2. PIN
3. password

Thank you in advance!

Kind Regards
Ioannis

**Comment by MartinKolarik** [comment]
See #50

**Comment by elethandor** [comment]
I didn't see that issue thank you.
