### ISSUE TITLE
KeePassWinHello incompatible with KeePass 2.45

### ISSUE THREAD

**Issue by foxxcomm** [sirAndros/KeePassWinHello#58]
KeePassWinHello incompatible with KeePass 2.45. Will not load the plug-in. Can we get a new build to fix? Thanks.

**Comment by RvdHout** [comment]
Latest KeePassWinHello (v3.1.1.0) works just fine with with KeePass 2.45

**Comment by foxxcomm** [comment]
Disregard - user error. Sorry about that. Our KeePass.exe.config file was old.
