### ISSUE TITLE
KeePassWinHello Error

### ISSUE THREAD

**Issue by JRMara** [sirAndros/KeePassWinHello#61]
**Describe the bug**
Error Message Pop Up at Program Start.
KeePass does not recognize WinHello.

**To Reproduce**
1. Download KeePass 3.1.1
2. Input Trigger

![image](https://user-images.githubusercontent.com/72266758/95724174-5106b380-0c76-11eb-8c1c-44890e684f27.png)

3. Install Plugin
4. Start KeePass

**Expected behavior**
After installing the Plugin I expected KeePass to recognize WinHello. 
Instead every time I start KeePass I get the Error message. 
KeePass starts normally after that, but does not recognize my WinHello.

**Screenshots**
![Screenshot 2020-10-02 163730](https://user-images.githubusercontent.com/72266758/95723648-a8f0ea80-0c75-11eb-8c68-23120170e0f5.png)

**Desktop (please complete the following information):**
 - OS Version - Win10 Enterprise
 - KeePass Version 3.1.1
 - Plugin Version KeePassWinHelloPlugin.plgx from Version 3.1.1
 - Dell Latitude 7400 + DELL UltraSharp U4919DW + Dell MS819 (fingerprint sensor)
 
 **KeePass settings and environment**
 - Is secure desktop enabled - No
 - Is KeePass running under Administrator (in elevated process) - Yes
 - Installed plugins - Yes see above
 

**Additional context**

**Comment by sirAndros** [comment]
Hello!
It's interesting. Can you check: does problem reproduce if you don't use trigger and try to open some database in clean KeePass with our plugin? (Also elevated, as you using it usually)

**Comment by JRMara** [comment]
I have deleted the trigger, rebooted my device and tried again. Same error, still does not recognize WinHello.

**Comment by sirAndros** [comment]
Thank you!
Please, tell us your windows version.
https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running
eg: 
![image](https://user-images.githubusercontent.com/1522711/95766844-2a676d80-0cb4-11eb-911a-2127a2198581.png)

**Comment by JRMara** [comment]
Windows specifications


Edition - Windows 10 Enterprise
Version - 1909
Installed on - 31.08.2020
OS build - 18363.1082

This registry property does not exist on my PC.

![Zwischenablage01](https://user-images.githubusercontent.com/72266758/95981208-92d25e00-0e1e-11eb-90a1-c7734a9d11d9.jpg)

**Comment by sirAndros** [comment]
Thank you! I will research your case in freetime

**Comment by shuffle-c** [comment]
Hi JRMara,
Can you please also let us know your current UAC settings? You can find it by typing 'uac' in the windows settings dialog:
![image](https://user-images.githubusercontent.com/3392944/96573775-e507f900-12ce-11eb-8273-84a89128ec15.png)
and you'll get something like this:
![image](https://user-images.githubusercontent.com/3392944/96573872-01a43100-12cf-11eb-8b48-0b08f832badb.png)

**Comment by JRMara** [comment]
![Zwischenablage01](https://user-images.githubusercontent.com/72266758/96698909-f2d08380-138d-11eb-94f1-3d62b9d0a868.jpg)

**Comment by shuffle-c** [comment]
Thank you, that's sufficient. As a current workaround, if you wish to, you can manually add the absent value EnableLUA to the registry:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableLUA"=dword:00000001
```

It won't affect your system since the value is meant for UAC being enabled which is actually enabled on your system anyway.
Meanwhile we'll fix the issue in the next release. Thank you for the report.

**Comment by JRMara** [comment]
Adding the "EnableLUA" value at 1 fixed the problem for me.
