### ISSUE TITLE
Invoking Windows Hello crashes other application using camera 

### ISSUE THREAD

**Issue by bar-foo-x** [sirAndros/KeePassWinHello#62]
**Describe the bug**
When an unlock is attempted using a Windows Hello camera that is in use by another application (in this case, Zoom), the other application is frozen/crashes. When some other applications are using the camera, KeePassWinHello reports that the camera is in use.

**To Reproduce**
1. Unlock KeePass
2. Lock KeePass
3. Open Zoom, start video in call
4. Attempt to unlock KeePass with KeePassWinHello via camera
5. Unlock successful
6. Video in Zoom freezes but audio works
7. After ~1 minute, Zoom crashes

**Expected behavior**
At step 4, Windows Hello should report that the camera is in use, ask for another login method.

**Desktop (please complete the following information):**
 - Windows 10 20H2
 - KeePass Version 2.46
 - Plugin Version 3.1.1.0
 - Hardware info: HP Elitebook x360 1030 G2 built-in webcam
 
 **KeePass settings and environment**
 - Is secure desktop enabled No
 - Is KeePass running under Administrator (in elevated process) No
 - Installed plugins (if any)
![image](https://user-images.githubusercontent.com/22479937/101428957-c15f4780-393c-11eb-9695-9a4d420b6714.png)
 - Any specific settings in KeePass/Plugin

**Comment by bar-foo-x** [comment]
A recent update to Zoom seems to have fixed this problem: Windows Hello now recognizes correctly that the camera is in use.

**Comment by sirAndros** [comment]
Unfortunately, its external applications issue, we can't do anything here.
