### ISSUE TITLE
[NCryptEncrypt - 0x80090026] NTE_INVALID_HANDLE

### ISSUE THREAD

**Issue by diver864** [sirAndros/KeePassWinHello#63]
My W10 PC went to sleep.  When I woke it back up, the following error message was on the screen:
![Keepass WinHello error 2021-01-08 172354](https://user-images.githubusercontent.com/14265676/104071612-82404280-51d7-11eb-9f6d-d8c7df4fb83b.jpg)

Keepass had locked, and when I brought it up from the system tray the WinHello plugin allowed me to reauthenticate using my W10 PIN as though nothing had happened.

I appreciate this plugin, so thank you!  First time I've ever encountered an issue with it.

**Comment by sirAndros** [comment]
Fixed in [v3.2](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.2)

**Comment by diver864** [comment]
Thank you!
