### ISSUE TITLE
[NCryptOpenKey - 0x80090016] NTE_BAD_KEYSET

### ISSUE THREAD

**Issue by bahaabeih** [sirAndros/KeePassWinHello#69]
**Describe the bug**
While KeePass has been minimized in the background for a while, I notice a popup showing an error (see below)

**To Reproduce**
Cannot

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/10739550/122545461-26070780-d02e-11eb-8cc0-a3b2e8d61118.png)

**Desktop (please complete the following information):**
 - Windows 10
 - KeePass Version 2.47
 - Plugin Version 3.1.1.0

**Comment by shuffle-c** [comment]
@bahaabeih 
Hi, could you please tell us whether you've enabled using persistent key (option Store keys in the Windows Credential Manager)? Have you encountered the issue again?

**Comment by bahaabeih** [comment]
No I didn't enable persistent keys.
 I haven't encountered the issue again

**Comment by sirAndros** [comment]
Fixed in [v3.2](https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.2)
