### ISSUE TITLE
NgcGetDefaultDecryptionKeyName

### ISSUE THREAD

**Issue by NZSmartie** [sirAndros/KeePassWinHello#8]
Hey @sirAndros,

You are using an undocumented function from Microsoft's Passport API here:

https://github.com/sirAndros/KeePassWinHello/blob/faa6048ab78fa8bcd95245f44d36bf5b3c0970fd/WinHello.cs#L17-L18

What does this function do?  Is it possible to create a new key specifically for the app instead of using the user's default key?

**Comment by shuffle-c** [comment]
Hi,

This function returns the default key name associated with current user's SID. It also possible to create a custom key, check out `CreatePersistentKey` method in `WinHelloProvider.cs` as an example of the algorithm.
