### ISSUE TITLE
How master password is stored in memory?

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [sirAndros/KeePassWinHello#83]
Missing detailed Description of how and when the master password is stored in memory.

1. Is the master password still stored in memory for usage of only QuickUnlock Feature while check "Store keys in the Windows Credential Manager" or no? Does it prevent it from storing in memory that can be accessed from outside Keepass?
 
2. How is the master password encrypted in memory ?

**Additional context**

https://github.com/sirAndros/KeePassWinHello#key-storage
https://github.com/sirAndros/KeePassWinHello/blob/b168c5a0847ff6192ea08e92dd3cc9bf458b2ef3/ReadMe.md?plain=1#L56-L59

**Comment by sirAndros** [comment]
Hi, @4-FLOSS-Free-Libre-Open-Source-Software!

Please check #104 and confirm if everything is clear now.
Thank you!

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Thanks for the clarification.
