### ISSUE TITLE
NullReferenceException: Plugin no longer working in Windows 11

### ISSUE THREAD

**Issue by phlox** [sirAndros/KeePassWinHello#85]
**Describe the bug**

After upgrading to Windows 11, the plugin is no longer working.

**To Reproduce**

1. Start KeePass 2
2. An error dialog is displayed "NullReferenceException ..."
3. Go to Tools > Options > WindowsHello
4. An error message is displayed "Windows Hello is disabled on your system. (...)" - which is not true.

**Expected behavior**

Working as it did in Windows 10

**Screenshots**
- ![Screenshot - 2021-12-15, 17_20_10](https://user-images.githubusercontent.com/1259743/146225377-8c032ecd-0591-40c4-a2c3-fbb87bb2876c.png)
- ![Screenshot - 2021-12-15, 17_23_36](https://user-images.githubusercontent.com/1259743/146225421-cdb17281-f22d-46a9-8ffa-db41ddad5744.png)

## Context

Please complete the following information:

| Component | Version |
|-----------|---------|
| Operating System | Windows 11 Pro 21H2 |
| KeePass |  2.49 (64 bit)|
| Plugin | 3.2.0.0 |

**Hardware info**

- AMD Ryzen 9 5950x / Asus ROG Strix X570-E
- Used biometric sensors: Face detection
- TPM module info (`Win`+`R` => `tpm.msc`)
 ![Screenshot - 2021-12-15, 17_34_26](https://user-images.githubusercontent.com/1259743/146226564-8d800570-763d-42ff-bd3c-d2a2455b4029.png)

 **Plugin settings**
 
 - [x] Is persistent mode enabled ("Store keys in Windows Credential Manager" checked)
 
 **KeePass settings and environment**
 
 - [ ] Is secure desktop enabled
 - [ ] Is KeePass running under Administrator (in elevated process)
 - [ ] Was it right after hibernation
 - [x] Was KeePass minified or closed
 
 - Installed plugins (if any)
![Screenshot - 2021-12-15, 17_37_14](https://user-images.githubusercontent.com/1259743/146227001-75e6b7ae-7513-41e8-8f74-21cb2b72a475.png)

**Additional context**

**Comment by shuffle-c** [comment]
Hello,
Can you please check if there is the key 'EnableLUA' in registry HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System?
If it's absent, please try to add it with the value 1 (DWORD).

Best wishes,
Sasha

**Comment by phlox** [comment]
Hi, 
that's weird, when i add this key, the key will be deleted after next reboot again:
1) after adding the key
![Screenshot - 2021-12-21, 17_07_17](https://user-images.githubusercontent.com/1259743/146962676-68007be4-3aab-492d-a6f6-a89b40d86ee9.png)
2) after reboot
![Screenshot - 2021-12-21, 17_11_20](https://user-images.githubusercontent.com/1259743/146962737-db4f38ef-d03c-4c28-893d-e6c16395bfef.png)

In the meanwhile, I have a second device (a Lenovo notebook) upgraded to Win 11 and there the WinHello plugin is working without any issues.

thanks for your help!

**Comment by shuffle-c** [comment]
@phlox, thank you for the update. We'll mitigate the absence of this flag in next release.

**Comment by sirAndros** [comment]
Merged in upcoming release
