### ISSUE TITLE
Remember original key file path

### ISSUE THREAD

**Issue by kinglike1337** [sirAndros/KeePassWinHello#9]
**Is your feature request related to a problem? Please describe.**
I use a key file as a part of the master password. If the WindowsHello timeout expired or keepass is restarted, the last used keyfile path is overridden with the WindowsHello key provider. 

**Describe the solution you'd like**
 It would be nice if the association to the last key file could be restored after timeout or restart.

**Describe alternatives you've considered**
I tried multiple config hacks (e.g. enforcement) to restore the key file path, but nothing worked.

**Additional context**
Kudos for this great plugin. It makes the usage of KeePass really smooth.

**Comment by sirAndros** [comment]
Hello!
I dived into part of sources of KeePass related to this issue and found no proper way to restore this information after successful login via WinHelo, but we have a few ideas how to build workaround for the issue, wanna try on weekend.

**Comment by kinglike1337** [comment]
Thanks for the info that sounds promising.

**Comment by shuffle-c** [comment]
Hi,

This turned out to be challenging task but finally we come up with the better solution and even more smooth user experience. So we completely reimplemented the plugin and are going to deliver version 2.0 soon.

Best wishes,
Sasha

**Comment by kinglike1337** [comment]
Thank for your great effort for this feature.
I am looking forward how this will turn out.

**Comment by shuffle-c** [comment]
Hi,

Sorry for the delay. Today we've finally published the new version.

Best wishes,
Sasha

**Comment by kinglike1337** [comment]
Thank you very much for your hard work on this huge commit.
The plugin now works really smooth.
