### ISSUE TITLE
Incompatible with KeePass version 2.49

### ISSUE THREAD

**Issue by Yagu-znal** [sirAndros/KeePassWinHello#90]
I get the message "Incompatible with version" at startup. Plugin still loads after clicking OK though. I'd love to see this streamlined.

Thanks for the work. Love your plugin!

**Comment by sirAndros** [comment]
Hello @Yagu-znal,
Can you please confirm that the problem is in our plugin? Maybe the massage comes from something else as I unable to confirm described behavior (works on my machine © :) ).
Thanks!

**Comment by sirAndros** [comment]
Unable to reproduce
