### ISSUE TITLE
KeePass Error with KeePassWinHelloPlugin.plgx and after Upgrade to Windows 11 22H2-22621

### ISSUE THREAD

**Issue by PRhodan** [sirAndros/KeePassWinHello#92]
Hello, 
I started a thread in KeePass Discussion, probably my problem is better here.
https://sourceforge.net/p/keepass/discussion/329221/thread/e3fb256ee8/
Greetings

**Comment by PRhodan** [comment]
@RueleuR
"(o) Store keys in the Windows Credential Manager"
Thx, I have changed this setting now, it does not have to be in the Windows credential manager.

**Comment by frostynumeral** [comment]
I can also confirm the issue after the upgrade to Win11 22H2. The suggestion to not store keys in the Windows Credential Manager also loses persistent key ability, so it's not really a good workaround.

**Comment by agrenott** [comment]
I didn't enable "(o) Store keys in the Windows Credential Manager", but the error popup still appears each time.

**Comment by DrFrankBV** [comment]
Same issue here. Always getting the error message when opening the DB. 
- Store in Windows Credential Manager is active
- When I deactivate this option then the Plugin does not work at all (the Hello prompt does not appear)

**Comment by DrFrankBV** [comment]
I think I found the root cause for this error:
It will occur only if you have "Enter Master Key on Secure Desktop" enabled in the KeePass Security settings..

I'll leave it to the developers to check if there is a way around it while leaving the option enabled. Maybe they could show at least a warning on the config page of the plugin, if the option is active or mention it in the know issues section of the Docu?

**Comment by PRhodan** [comment]
DrFrankBV, yes I have "Enter Master Key on Secure Desktop" enabled.
And yes, you have found the root cause for this error.
Thanks!

**Comment by OrihalconDE** [comment]
Wow, that's some pain in the ass.
So we now have to choose between a security feature preventing keylogging or keeping our comfort with windows hello and giving up on security.
Thank you Windows for this shit.

**Comment by PRhodan** [comment]
https://github.com/sirAndros/KeePassWinHello/releases/tag/v3.2
Aug 19, 2021 !
