### ISSUE TITLE
Option to Trigger auto-type hotkey after auth?

### ISSUE THREAD

**Issue by sirtet** [sirAndros/KeePassWinHello#95]
I want to further automate KeePass's auto-type Feature beyond what it already can do.
It would be nice to instead of pressing the auto-type Hotkey combination to just scan a finger and the rest is automated.

It seems to me to achieve that,  all that would be needed would be that after this plugin opens a keepass database, send the auto-type hotkey? Or maybe auto-type can directly be triggered by the plugin?

My actual usecase is a bit more complicated, like this:
I have a Windows program that shows a user/password dialogue on startup. About 20 different users have to log in into it. 
I want to completely automate this, so only a finger-scan is needed to log in a user.
The Windows user stays the same, no log-in/out between different users. If needed, a separate Windows login could be created per user.

Maybe there already exists a different, more elegant way to do what i want?

**Comment by sirAndros** [comment]
Hello!
I use KeePass as you described: Focus username(or password) field, press `CTRL`+`ALT`+`A`, scan my finger and KeePass just do the rest right from the box.
For your case there is also native capability called "AutoType Customization for Entry":
![image](https://user-images.githubusercontent.com/1522711/218880435-04841aa4-3fca-4619-a696-75595da5342f.png)

More information: [official site](https://keepass.info/help/base/autotype.html)

**Comment by sirtet** [comment]
Thanks.
Yes, that's what i figured out should be possible already.
But now i imagine it should be not too hard to trigger the `CTRL`+`ALT`+`A` combination by the successful finger scan.
I can't expect all the users to remember this Hotkey. They have to log in not very regularly, that's also why i want them to be able to log in via fingerprint, so they also don't have to remember a username/password.

**Comment by sirAndros** [comment]
But how do you trigger fingerprint scan without triggering autotype in first place?
Do you want to scan fingerprint continuesly after computer start?

**Comment by sirtet** [comment]
Oh, I expected scanning a Finger would already trigger this plugin to Unlock KeePass...
That’s not the case then?

**Comment by sirAndros** [comment]
No, KeePass initiate quering fingerprint scaner when it's trying to unlock db

**Comment by sirAndros** [comment]
Could we close the issue?

**Comment by sirtet** [comment]
Yes. or... actually, if i may, i have another question:
What's the reason to initiate the scan by KeePass, not the other way round?
Is there a technical limit, or would it go against something in the program's logic?

**Comment by sirAndros** [comment]
The tech we use in plugin (Windows Hello) assumes using on demand (you can't use it to poll fingerprint sensor). But there is direct biometrics API in WinNative, maybe it can contains something like that, I didn't recearch it.
If it does not, I see only driver hijack architecture, but it looks overcompicated and demands you to use the same hardware for all your users, so direct answer - you can't.
But maybe there are other ways? E.g. [AHK](https://www.autohotkey.com) script which will trigger keepass autotype when specific window opens or something like that? Check out scripting API of KeePass: https://keepass.info/help/base/cmdline.html, but I believe that `KeePass.exe -auto-type` is enough for your case

**Comment by sirtet** [comment]
Thanks a lot for the elaboration and ideas.

**Comment by sirAndros** [comment]
You are welcome!
