### ISSUE TITLE
KeePassWinHello keeps saying that WinHello is unavailable

### ISSUE THREAD

**Issue by mfountouklis** [sirAndros/KeePassWinHello#96]
Hi, and first and foremost thank you for your awesome work and contribution.
Been trying to install this plugin on an office computer which is part of a domain,
i've enabled WinHello fingerprint login via GPO and i can logon into my PC via fingerprint
(Kesington VeriMark USB fingerprint reader). Im running windows 11 Pro 22H2.

When i go into Keepass options it tells me that WinHello is not available on my computer and 
doesnt let me setup anything.

Is it a bug im not sure, or maybe im missing something! THank you!

EDIT: im stupid, i had only setup fingerprint and not PIN. Now seems to be working. Sorry

**Comment by sirAndros** [comment]
Hi!
Glad you make it works!
Hope your IT & SecOps guys don't mind ;-)
