### ISSUE TITLE
Debugging KeePassWinHello in Visual Studio 2022 throws exception

### ISSUE THREAD

**Issue by frostynumeral** [sirAndros/KeePassWinHello#97]
Debugging KeePassWinHello in Visual Studio 2022 throws InvalidOperationException: Cross-thread operation not valid: Control 'MainForm' accessed from a thread other than the thread it was created on.

![KeepPassWinHelloDebug](https://user-images.githubusercontent.com/22858982/224427717-9ad6cb5f-b221-43cf-a3df-9bbb431530c8.png)

How is it possible to debug this plugin?

**Comment by sirAndros** [comment]
Hi! It's looks like KeePass plugin architecture has changed and now KeePass runs us in separate thread (not the UI one as before).
Or maybe it something with WinForms in win11, as we have several issues with this OS and both me and @shuffle-c still using win10. And I have latest KeePass version btw, and on my machine latest release version of the plugin works great (except WinHello window have sometimes been hidden by some other windows, but I still don't know how to fight it and we have separate issue for it).
Anyway, thanks for clues and please stay in touch if we need further info. Also if you fix it by your own, PRs are very welcome ;-)

**Comment by frostynumeral** [comment]
Hi @sirAndros! Thank you for the explanation about the KeePass plugin architecture. On my Windows 10 machine the plugin works fine, I only have issues on Windows 11.
